### ISSUE TITLE
Which interface is required for a new backend?

### ISSUE THREAD

**Issue by stephenwithav** [vimukthi-git/beanstalkg#16]
Is it `PriorityQueue`?

**Comment by vimukthi-git** [comment]
yes, If you like to try implementing a new backend I've marked the `PriorityQueue` interface methods you need to implement. I would like to see some alternate storage implemented may be on a `Redis` backend.

**Comment by stephenwithav** [comment]
Thank you.  I'm going to try implementing `PriorityQueue` and `PriorityQueueItem` with either MySQL or PostgreSQL for persistence.
