### ISSUE TITLE
architecture: log redeclared in this block

### ISSUE THREAD

**Issue by stephenwithav** [vimukthi-git/beanstalkg#18]
`queue.go` has a `var log = logging.MustGetLogger("BEANSTALKG")` and `job.go` imports `github.com/labstack/gommon/log`, which causes the conflict.

Kill the `github.com/labstack/gommon/log` import?

**Comment by vimukthi-git** [comment]
We do not currently import `github.com/labstack/gommon/log` anywhere right now. Could you explain?

**Comment by stephenwithav** [comment]
My emacs buffer maintained the copy of `job.go` with with gommon/lock.  Apologies.
