### ISSUE TITLE
Add a docker file and dockerize beanstalkg

### ISSUE THREAD

**Issue by vimukthi-git** [vimukthi-git/beanstalkg#19]
Add a docker file and dockerize beanstalkg, so that it can be run easily in a container environment

**Comment by stephenwithav** [comment]
Do you want a container that compiles beanstalkg (which would include the go compiler) or one that contains the beanstalkg binary minus the go compiler?

**Comment by vimukthi-git** [comment]
Just the binary is good I think.

**Comment by stephenwithav** [comment]
That PR will be up this afternoon.

**Comment by stephenwithav** [comment]
Which base image do you use for your other containers?  debian?  ubuntu?  fedora?

**Comment by stephenwithav** [comment]
Done.
