### ISSUE TITLE
Add beanstalkg to queues.io

### ISSUE THREAD

**Issue by stephenwithav** [vimukthi-git/beanstalkg#23]
PR here: https://github.com/lukaszx0/queues.io/pull/120

Queues.io: http://queues.io/

Hopefully this can get you more exposure.

**Comment by vimukthi-git** [comment]
great thank you very much @stephenwithav . I hope it will get accepted. I will find more time to spend on this project, Since I have a collaborator to help me :)
(I never wrote the next parts of my blog series about the queue, I will start writing it now)

**Comment by stephenwithav** [comment]
It has been accepted, but the site hasn't been updated yet.

I look forward to the next parts of your series!
