### ISSUE TITLE
Rename log instances to logg.

### ISSUE THREAD

**Issue by stephenwithav** [vimukthi-git/beanstalkg#69]
Problem: a pre-save hook runs `goimports` to format the `go` files and automatically adds missing imports.  When `log` is referenced outside of the file it is defined, `goimports` chooses from the packages you have defined.  In my case, `goimports` prefers `gommon/log`.

Workaround: rename instances of `log` to `logg` to prevent `goimports` from addiing `gommon/log` every time.

Any objections? :)

**Comment by vimukthi-git** [comment]
we can make it `logger` that would look better right?

**Comment by stephenwithav** [comment]
`logger` conflicts with many existing packages. e.g., https://godoc.org/github.com/coreos/rkt/tests/testutils/logger

Switching `log` to `logger` in `architecture/{job,protocol,tube}.go` imports the above package in `job.go` on save.

**Comment by vimukthi-git** [comment]
we can explicitly create a logger in every file we need.

Do you see any problem with that? Otherwise naming this way seems kind of weird.

**Comment by vimukthi-git** [comment]
Where is this pre save hook added? I can not find it in the repo?

**Comment by vimukthi-git** [comment]
I also noticed just now when I was trying to test some of your changes locally that the logging seems to misbehave when I run it. For example debug logs show up even though I have not enabled it.

**Comment by stephenwithav** [comment]
Explicitly creating a logger works.

**Comment by stephenwithav** [comment]
The pre-save hook is in my emacs config.

Try calling goimports on save.

**Comment by vimukthi-git** [comment]
closing this as the solution is explicitly creating a logger.
